FROM php:7.4-fpm
    
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions gd zip pdo_mysql
  
COPY --from=composer /usr/bin/composer /usr/bin/composer

